### ISSUE TITLE
Importing RSA is slow (~150ms)

### ISSUE THREAD

**Issue by paravoid** [Legrandin/pycryptodome#328]
In a clean venv, with Python 3.7, and with just pycrypto (2.6.1) and pycryptodomex (3.9.0) installed and warm caches:
```
$ time python3 -c "from Crypto.PublicKey import RSA"

real    0m0,036s
user    0m0,032s
sys     0m0,004s

$ time python3 -c "from Cryptodome.PublicKey import RSA"

real    0m0,169s
user    0m0,117s
sys     0m0,059s
```

130-150ms overhead is pretty significant and especially for e.g. a CLI program. I only started investigating it because it was noticeable on my shell.

I also tried installing cffi (which I noticed changes some of the code paths), but it did not make a difference. cProfile has been unhelpful, but perhaps someone more familiar with the codebase could make more sense of this. Thanks for all of your efforts!

**Comment by Legrandin** [comment]
Thanks for flagging this - I will try to use the `-X importtime` option to see where the time is spent...

**Comment by Legrandin** [comment]
Actually, cffi does actually slow down the import, because it pulls in its parsers.
On my system, with pycrypto:

```
$ time python -c "from Crypto.PublicKey import RSA"

real    0m0.054s
user    0m0.046s
sys     0m0.008s
```

While with  pycryptodomex version 3.9.0  without `cffi` installed:
```
$ time python -c "from Cryptodome.PublicKey import RSA"

real    0m0.180s
user    0m0.120s
sys     0m0.066s
```

With version 3.9.0 and with `cffi`:

```
$ time python -c "from Cryptodome.PublicKey import RSA"

real    0m0.214s
user    0m0.193s
sys     0m0.021s
```

I just released a new version 3.9.1 with some simple optimizations. Without `cffi`:
```
$ time python -c "from Cryptodome.PublicKey import RSA"

real    0m0.084s
user    0m0.071s
sys     0m0.013s
```
And version 3.9.1 with `cffi`:
```
$ time python -c "from Cryptodome.PublicKey import RSA"

real    0m0.132s
user    0m0.116s
sys     0m0.016s
```

It doesn't seem it is easy to do much better than that, especially if `cffi` is installed.

**Comment by Tilka** [comment]
This is still an issue, at least for AES. Why prefer cffi over ctypes if it's so slow to import it?

With cffi installed:
```sh
$ time python -c 'from Crypto.Cipher import AES'

real	0m0.324s
user	0m0.268s
sys	0m0.071s
```

Without cffi installed:
```sh
$ time python -c 'from Crypto.Cipher import AES'

real	0m0.034s
user	0m0.031s
sys	0m0.003s
```

This is on a Ryzen 9 3950X.
